/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export type VEHICLEINFOStruct = {
  vehicleType: BigNumberish;
  vehicleDocumentsUrl: string;
  vehicle_no: string;
  owner: string;
};

export type VEHICLEINFOStructOutput = [number, string, string, string] & {
  vehicleType: number;
  vehicleDocumentsUrl: string;
  vehicle_no: string;
  owner: string;
};

export type RIDEINFOStruct = {
  driver: string;
  customer: string;
  pickup: string;
  destination: string;
  distance: BigNumberish;
  vehicle: VEHICLEINFOStruct;
  price: BigNumberish;
  noOfPassengers: BigNumberish;
  isCancelled: boolean;
  isComplete: boolean;
  wasCancelledBy: BigNumberish;
  bookingTime: string;
  completeTime: string;
  cancelledTime: string;
};

export type RIDEINFOStructOutput = [
  string,
  string,
  string,
  string,
  BigNumber,
  VEHICLEINFOStructOutput,
  BigNumber,
  BigNumber,
  boolean,
  boolean,
  number,
  string,
  string,
  string
] & {
  driver: string;
  customer: string;
  pickup: string;
  destination: string;
  distance: BigNumber;
  vehicle: VEHICLEINFOStructOutput;
  price: BigNumber;
  noOfPassengers: BigNumber;
  isCancelled: boolean;
  isComplete: boolean;
  wasCancelledBy: number;
  bookingTime: string;
  completeTime: string;
  cancelledTime: string;
};

export type RIDEStruct = { rideId: BigNumberish; rideDetails: RIDEINFOStruct };

export type RIDEStructOutput = [BigNumber, RIDEINFOStructOutput] & {
  rideId: BigNumber;
  rideDetails: RIDEINFOStructOutput;
};

export interface RideInterface extends utils.Interface {
  functions: {
    "addVehicle(address,string,string,uint8)": FunctionFragment;
    "confirmRide((address,address,string,string,uint256,(uint8,string,string,address),uint256,uint256,bool,bool,uint8,string,string,string))": FunctionFragment;
    "getAllRides(uint256[])": FunctionFragment;
    "getRide(uint256)": FunctionFragment;
    "getVehicle(address)": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addVehicle",
    values: [string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmRide",
    values: [RIDEINFOStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllRides",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getRide",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getVehicle", values: [string]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "addVehicle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confirmRide",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllRides",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRide", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getVehicle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  { previousOwner: string; newOwner: string }
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface Ride extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RideInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addVehicle(
      owner: string,
      vehicleDocumentsUrl: string,
      vehicle_no: string,
      vehicleType: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    confirmRide(
      _rideDetails: RIDEINFOStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getAllRides(
      rideIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<[RIDEStructOutput[]]>;

    getRide(
      _rideId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[RIDEStructOutput]>;

    getVehicle(
      owner: string,
      overrides?: CallOverrides
    ): Promise<[VEHICLEINFOStructOutput]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  addVehicle(
    owner: string,
    vehicleDocumentsUrl: string,
    vehicle_no: string,
    vehicleType: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  confirmRide(
    _rideDetails: RIDEINFOStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getAllRides(
    rideIds: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<RIDEStructOutput[]>;

  getRide(
    _rideId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<RIDEStructOutput>;

  getVehicle(
    owner: string,
    overrides?: CallOverrides
  ): Promise<VEHICLEINFOStructOutput>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addVehicle(
      owner: string,
      vehicleDocumentsUrl: string,
      vehicle_no: string,
      vehicleType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    confirmRide(
      _rideDetails: RIDEINFOStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAllRides(
      rideIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<RIDEStructOutput[]>;

    getRide(
      _rideId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<RIDEStructOutput>;

    getVehicle(
      owner: string,
      overrides?: CallOverrides
    ): Promise<VEHICLEINFOStructOutput>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    addVehicle(
      owner: string,
      vehicleDocumentsUrl: string,
      vehicle_no: string,
      vehicleType: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    confirmRide(
      _rideDetails: RIDEINFOStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getAllRides(
      rideIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRide(
      _rideId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getVehicle(owner: string, overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addVehicle(
      owner: string,
      vehicleDocumentsUrl: string,
      vehicle_no: string,
      vehicleType: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    confirmRide(
      _rideDetails: RIDEINFOStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getAllRides(
      rideIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRide(
      _rideId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getVehicle(
      owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
