/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type OwnershipTransferred = ContractEventLog<{
  previousOwner: string;
  newOwner: string;
  0: string;
  1: string;
}>;

export interface Ride extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): Ride;
  clone(): Ride;
  methods: {
    addVehicle(
      driver: string,
      _vehicle: [string, string, string, number | string | BN, string]
    ): NonPayableTransactionObject<void>;

    cancelRide(
      _rideId: number | string | BN,
      _wasCancelledBy: number | string | BN,
      _timestamp: string
    ): NonPayableTransactionObject<void>;

    completeRide(
      _rideId: number | string | BN,
      _timestamp: string
    ): NonPayableTransactionObject<void>;

    confirmRide(
      _user: [string, string],
      _status: [boolean, boolean, boolean, number | string | BN],
      _details: [string, string, number | string | BN, number | string | BN],
      _timestamp: string
    ): NonPayableTransactionObject<string>;

    getAllRides(
      rideIds: (number | string | BN)[]
    ): NonPayableTransactionObject<
      [
        string,
        [string, string],
        [boolean, boolean, boolean, string],
        [string, string, string, string],
        [string, string, string, string, string],
        string
      ][]
    >;

    getRide(
      _rideId: number | string | BN
    ): NonPayableTransactionObject<
      [
        string,
        [string, string],
        [boolean, boolean, boolean, string],
        [string, string, string, string],
        [string, string, string, string, string],
        string
      ]
    >;

    getRideCount(): NonPayableTransactionObject<string>;

    getVehicle(
      driver: string
    ): NonPayableTransactionObject<[string, string, string, string, string]>;

    /**
     * Returns the address of the current owner.
     */
    owner(): NonPayableTransactionObject<string>;

    /**
     * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions anymore. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby removing any functionality that is only available to the owner.
     */
    renounceOwnership(): NonPayableTransactionObject<void>;

    /**
     * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
     */
    transferOwnership(newOwner: string): NonPayableTransactionObject<void>;

    updateVehicle(
      driver: string,
      _vehicle: [string, string, string, number | string | BN, string]
    ): NonPayableTransactionObject<void>;
  };
  events: {
    OwnershipTransferred(cb?: Callback<OwnershipTransferred>): EventEmitter;
    OwnershipTransferred(
      options?: EventOptions,
      cb?: Callback<OwnershipTransferred>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "OwnershipTransferred", cb: Callback<OwnershipTransferred>): void;
  once(
    event: "OwnershipTransferred",
    options: EventOptions,
    cb: Callback<OwnershipTransferred>
  ): void;
}
