/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PriToken } from './PriToken';
export type { Ride } from './Ride';
export * as factories from './factories';
export { PriToken__factory } from './factories/PriToken__factory';
export { Ride__factory } from './factories/Ride__factory';
